time_series_path = raw"C:\Users\brigatto\Documents\GitHub\InflowForecastBias_Data\CompareScenariosGenerators\NIE.csv"
num_steps_ahead = 24
num_scenarios = 1
num_windows = 165
fixed_forecast_window_size = false
model_executable_path = raw"C:\Users\brigatto\Documents\GitHub\InflowForecastBias_Data\CompareScenariosGenerators\model_ALTM\ALTM.bat"
model_name = "ALTM"
plot_all_scenarios_windows = true